## Basic Configuration
baseurl = "/"
languageCode = "en-us"
canonifyURLs = true

title = "XenoBlog"
theme = "hyde-hyde"

## Hugo Built-in Features
  disqusShortname = "xipher-1"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

 summarylength = 30

 paginate = 10

## Site Settings
[params]
    author = "Claus T Nielsen"
    title = "XenoBlog"
    # description = "Random ramblings"
    authorimage = "/assets/images/me.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "Xenophane"
    since = 2007
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "dracula"
    highlightjslanguages = ["powershell", "sql"]
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "claustn"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "claustn"
    twitter = "claustn"
    facebook = "claus.t.nielsen.37"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "claustnspam@gmail.com"
    # gravatar = "claustn@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "AboutMe"
    identifier = "about"
    weight = 300
    url = "/about/"